import db from "@/lib/db";

async function main() {
  await db.menuItem.createMany({
    data: [
      {
        name: "Bruschetta",
        description:
          "Toasted bread topped with tomatoes, garlic, and fresh basil",
        price: 8.99,
        category: "APPETIZER",
        preparationStation: "KITCHEN",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800&auto=format&fit=crop",
        calories: 250,
        ingredients: ["Bread", "Tomatoes", "Garlic", "Basil", "Olive Oil"],
        tags: ["Italian", "Fresh", "Light"],
      },
      {
        name: "Garlic Bread",
        description: "Crusty bread with garlic butter and herbs",
        price: 6.99,
        category: "APPETIZER",
        preparationStation: "KITCHEN",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w-800&auto=format&fit=crop",
        calories: 320,
        ingredients: ["French Bread", "Garlic", "Butter", "Parsley"],
        tags: ["Classic", "Garlic", "Warm"],
      },
      {
        name: "Chicken Wings",
        description: "Crispy chicken wings with buffalo sauce",
        price: 12.99,
        category: "APPETIZER",
        preparationStation: "FRY_STATION",
        isVegetarian: false,
        isSpicy: true,
        preparationTime: 15,
        imageUrl:
          "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w-800&auto=format&fit=crop",
        calories: 450,
        ingredients: ["Chicken Wings", "Buffalo Sauce", "Butter", "Celery"],
        tags: ["Spicy", "Crispy", "Shareable"],
      },
      {
        name: "Spring Rolls",
        description: "Vegetable spring rolls with sweet chili sauce",
        price: 9.99,
        category: "APPETIZER",
        preparationStation: "FRY_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 12,
        imageUrl:
          "https://images.unsplash.com/photo-1563245372-f21724e3856d?w-800&auto=format&fit=crop",
        calories: 280,
        ingredients: ["Rice Paper", "Carrots", "Cabbage", "Mushrooms"],
        tags: ["Asian", "Crispy", "Light"],
      },
      {
        name: "Mozzarella Sticks",
        description: "Breaded mozzarella sticks with marinara sauce",
        price: 10.99,
        category: "APPETIZER",
        preparationStation: "FRY_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&auto=format&fit=crop",
        calories: 380,
        ingredients: ["Mozzarella", "Breadcrumbs", "Marinara Sauce"],
        tags: ["Cheesy", "Fried", "Classic"],
      },
      {
        name: "Shrimp Cocktail",
        description: "Chilled shrimp with cocktail sauce",
        price: 14.99,
        category: "APPETIZER",
        preparationStation: "KITCHEN",
        isVegetarian: false,
        isSpicy: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1605209671121-7c4a8f5d85d3?w-800&auto=format&fit=crop",
        calories: 180,
        ingredients: ["Shrimp", "Cocktail Sauce", "Lemon"],
        tags: ["Seafood", "Cold", "Elegant"],
      },
      // MAIN_COURSE
      {
        name: "Grilled Salmon",
        description: "Atlantic salmon with lemon butter sauce",
        price: 24.99,
        category: "MAIN_COURSE",
        preparationStation: "GRILL_STATION",
        isVegetarian: false,
        isSpicy: false,
        preparationTime: 20,
        imageUrl:
          "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&auto=format&fit=crop",
        calories: 520,
        ingredients: ["Salmon", "Lemon", "Butter", "Dill", "Asparagus"],
        tags: ["Seafood", "Healthy", "Grilled"],
      },
      {
        name: "Ribeye Steak",
        description: "12oz ribeye with garlic herb butter",
        price: 32.99,
        category: "MAIN_COURSE",
        preparationStation: "GRILL_STATION",
        isVegetarian: false,
        isSpicy: false,
        preparationTime: 25,
        imageUrl:
          "https://images.unsplash.com/photo-1600891964092-4316c288032e?w-800&auto=format&fit=crop",
        calories: 780,
        ingredients: ["Ribeye Steak", "Garlic", "Herbs", "Butter"],
        tags: ["Steak", "Premium", "Grilled"],
      },
      {
        name: "Mushroom Risotto",
        description: "Creamy arborio rice with wild mushrooms",
        price: 18.99,
        category: "MAIN_COURSE",
        preparationStation: "KITCHEN",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 22,
        imageUrl:
          "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w-800&auto=format&fit=crop",
        calories: 420,
        ingredients: ["Arborio Rice", "Mushrooms", "Parmesan", "White Wine"],
        tags: ["Vegetarian", "Creamy", "Italian"],
      },
      {
        name: "Chicken Alfredo Pasta",
        description: "Fettuccine with creamy alfredo sauce and grilled chicken",
        price: 19.99,
        category: "MAIN_COURSE",
        preparationStation: "KITCHEN",
        isVegetarian: false,
        isSpicy: false,
        preparationTime: 18,
        imageUrl:
          "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w-800&auto=format&fit=crop",
        calories: 650,
        ingredients: ["Fettuccine", "Chicken", "Cream", "Parmesan"],
        tags: ["Pasta", "Creamy", "Classic"],
      },
      {
        name: "Vegetable Curry",
        description: "Mixed vegetables in aromatic coconut curry",
        price: 16.99,
        category: "MAIN_COURSE",
        preparationStation: "KITCHEN",
        isVegetarian: true,
        isSpicy: true,
        preparationTime: 20,
        imageUrl:
          "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w-800&auto=format&fit=crop",
        calories: 380,
        ingredients: [
          "Mixed Vegetables",
          "Coconut Milk",
          "Curry Paste",
          "Rice",
        ],
        tags: ["Vegetarian", "Spicy", "Asian"],
      },
      {
        name: "Fish and Chips",
        description: "Beer-battered cod with french fries",
        price: 21.99,
        category: "MAIN_COURSE",
        preparationStation: "FRY_STATION",
        isVegetarian: false,
        isSpicy: false,
        preparationTime: 15,
        imageUrl:
          "https://images.unsplash.com/photo-1579208030886-b937da0925dc?w=800&auto=format&fit=crop",
        calories: 680,
        ingredients: ["Cod", "Beer Batter", "Potatoes", "Tartar Sauce"],
        tags: ["Seafood", "British", "Fried"],
      },
      // DESSERTS
      {
        name: "Chocolate Lava Cake",
        description: "Warm chocolate cake with molten center",
        price: 9.99,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 12,
        imageUrl:
          "https://images.unsplash.com/photo-1624353365286-3f8d62dadadf?w=800&auto=format&fit=crop",
        calories: 480,
        ingredients: [
          "Chocolate",
          "Butter",
          "Eggs",
          "Flour",
          "Vanilla Ice Cream",
        ],
        tags: ["Chocolate", "Warm", "Popular"],
      },
      {
        name: "New York Cheesecake",
        description: "Classic cheesecake with berry compote",
        price: 8.99,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=800&auto=format&fit=crop",
        calories: 420,
        ingredients: ["Cream Cheese", "Graham Cracker", "Berries", "Sugar"],
        tags: ["Classic", "Creamy", "Cold"],
      },
      {
        name: "Tiramisu",
        description: "Italian coffee-flavored dessert",
        price: 10.99,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop",
        calories: 380,
        ingredients: ["Ladyfingers", "Mascarpone", "Coffee", "Cocoa"],
        tags: ["Italian", "Coffee", "Layered"],
      },
      {
        name: "Apple Pie",
        description: "Homemade apple pie with vanilla ice cream",
        price: 7.99,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1561626423-a51b45aef0a4?w-800&auto=format&fit=crop",
        calories: 320,
        ingredients: ["Apples", "Cinnamon", "Pie Crust", "Vanilla Ice Cream"],
        tags: ["Classic", "Warm", "Fruity"],
      },
      {
        name: "Crème Brûlée",
        description: "Rich custard with caramelized sugar top",
        price: 11.99,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&auto=format&fit=crop",
        calories: 350,
        ingredients: ["Cream", "Egg Yolks", "Sugar", "Vanilla"],
        tags: ["French", "Creamy", "Caramelized"],
      },
      {
        name: "Brownie Sundae",
        description: "Warm brownie with ice cream and hot fudge",
        price: 12.99,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=800&auto=format&fit=crop",
        calories: 580,
        ingredients: [
          "Brownie",
          "Vanilla Ice Cream",
          "Hot Fudge",
          "Whipped Cream",
        ],
        tags: ["Chocolate", "Indulgent", "Warm"],
      },
      // BEVERAGES
      {
        name: "Fresh Orange Juice",
        description: "Freshly squeezed orange juice",
        price: 4.99,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 3,
        imageUrl:
          "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w-800&auto=format&fit=crop",
        calories: 120,
        ingredients: ["Oranges"],
        tags: ["Fresh", "Healthy", "Cold"],
      },
      {
        name: "Iced Coffee",
        description: "Cold brew coffee with milk",
        price: 5.99,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&auto=format&fit=crop",
        calories: 80,
        ingredients: ["Coffee", "Milk", "Ice"],
        tags: ["Coffee", "Cold", "Refreshing"],
      },
      {
        name: "Lemonade",
        description: "Homemade lemonade",
        price: 3.99,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 4,
        imageUrl:
          "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w-800&auto=format&fit=crop",
        calories: 100,
        ingredients: ["Lemons", "Sugar", "Water"],
        tags: ["Refreshing", "Sweet", "Cold"],
      },
      {
        name: "Green Tea",
        description: "Hot green tea",
        price: 3.49,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 3,
        imageUrl:
          "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&auto=format&fit=crop",
        calories: 0,
        ingredients: ["Green Tea", "Hot Water"],
        tags: ["Hot", "Healthy", "Tea"],
      },
      {
        name: "Sparkling Water",
        description: "Carbonated water with lemon",
        price: 2.99,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 2,
        imageUrl:
          "https://images.unsplash.com/photo-1599031628962-1f6755a3b1b7?w=800&auto=format&fit=crop",
        calories: 0,
        ingredients: ["Carbonated Water", "Lemon"],
        tags: ["Sparkling", "Refreshing", "Zero Calorie"],
      },
      {
        name: "Hot Chocolate",
        description: "Rich hot chocolate with whipped cream",
        price: 4.99,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 6,
        imageUrl:
          "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w-800&auto=format&fit=crop",
        calories: 280,
        ingredients: ["Chocolate", "Milk", "Whipped Cream"],
        tags: ["Hot", "Chocolate", "Comforting"],
      },
      // ALCOHOLIC
      {
        name: "Classic Margarita",
        description: "Tequila, lime juice, and triple sec",
        price: 12.99,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&auto=format&fit=crop",
        calories: 220,
        ingredients: ["Tequila", "Lime Juice", "Triple Sec"],
        tags: ["Cocktail", "Classic", "Margarita"],
      },
      {
        name: "Old Fashioned",
        description: "Whiskey, sugar, and bitters",
        price: 14.99,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 6,
        imageUrl:
          "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&auto=format&fit=crop",
        calories: 180,
        ingredients: ["Whiskey", "Sugar", "Bitters", "Orange"],
        tags: ["Cocktail", "Classic", "Strong"],
      },
      {
        name: "Pinot Noir",
        description: "Glass of premium Pinot Noir",
        price: 9.99,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 2,
        imageUrl:
          "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&auto=format&fit=crop",
        calories: 120,
        ingredients: ["Pinot Noir Wine"],
        tags: ["Wine", "Red", "Premium"],
      },
      {
        name: "Chardonnay",
        description: "Glass of oak-aged Chardonnay",
        price: 8.99,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 2,
        imageUrl:
          "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&auto=format&fit=crop",
        calories: 110,
        ingredients: ["Chardonnay Wine"],
        tags: ["Wine", "White", "Oaky"],
      },
      {
        name: "Local Craft Beer",
        description: "Pint of local IPA",
        price: 7.99,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 2,
        imageUrl:
          "https://images.unsplash.com/photo-1571613316887-6f8d5cbf7ef7?w=800&auto=format&fit=crop",
        calories: 200,
        ingredients: ["IPA Beer"],
        tags: ["Beer", "Craft", "Local"],
      },
      {
        name: "Mojito",
        description: "Rum, mint, lime, and soda water",
        price: 11.99,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 7,
        imageUrl:
          "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&auto=format&fit=crop",
        calories: 190,
        ingredients: ["Rum", "Mint", "Lime", "Soda Water"],
        tags: ["Cocktail", "Refreshing", "Minty"],
      },
      // SNACKS
      {
        name: "French Fries",
        description: "Crispy golden french fries",
        price: 5.99,
        category: "SNACK",
        preparationStation: "FRY_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1576107232684-1279f390859f?w-800&auto=format&fit=crop",
        calories: 320,
        ingredients: ["Potatoes", "Salt", "Oil"],
        tags: ["Crispy", "Classic", "Shareable"],
      },
      {
        name: "Onion Rings",
        description: "Beer-battered onion rings",
        price: 6.99,
        category: "SNACK",
        preparationStation: "FRY_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1639024471284-801f6bd6c1e0?w=800&auto=format&fit=crop",
        calories: 380,
        ingredients: ["Onions", "Beer Batter", "Oil"],
        tags: ["Crispy", "Onion", "Fried"],
      },
      {
        name: "Nachos",
        description: "Tortilla chips with cheese and jalapeños",
        price: 11.99,
        category: "SNACK",
        preparationStation: "KITCHEN",
        isVegetarian: true,
        isSpicy: true,
        preparationTime: 12,
        imageUrl:
          "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop",
        calories: 450,
        ingredients: ["Tortilla Chips", "Cheese", "Jalapeños", "Salsa"],
        tags: ["Shareable", "Cheesy", "Spicy"],
      },
      {
        name: "Garlic Parmesan Fries",
        description: "French fries with garlic and parmesan",
        price: 7.99,
        category: "SNACK",
        preparationStation: "FRY_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1576107232684-1279f390859f?w-800&auto=format&fit=crop",
        calories: 380,
        ingredients: ["Potatoes", "Garlic", "Parmesan", "Parsley"],
        tags: ["Garlic", "Cheesy", "Upgraded"],
      },
      {
        name: "Sweet Potato Fries",
        description: "Crispy sweet potato fries",
        price: 6.99,
        category: "SNACK",
        preparationStation: "FRY_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1576107232684-1279f390859f?w-800&auto=format&fit=crop",
        calories: 280,
        ingredients: ["Sweet Potatoes", "Salt", "Oil"],
        tags: ["Sweet", "Healthy", "Alternative"],
      },
      {
        name: "Mozzarella Bites",
        description: "Bite-sized mozzarella cheese sticks",
        price: 8.99,
        category: "SNACK",
        preparationStation: "FRY_STATION",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&auto=format&fit=crop",
        calories: 320,
        ingredients: ["Mozzarella", "Breadcrumbs", "Marinara"],
        tags: ["Cheesy", "Bite-sized", "Shareable"],
      },
      // SIDE_DISHES
      {
        name: "Garlic Mashed Potatoes",
        description: "Creamy mashed potatoes with roasted garlic",
        price: 4.99,
        category: "SIDE_DISH",
        preparationStation: "KITCHEN",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 12,
        imageUrl:
          "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w-800&auto=format&fit=crop",
        calories: 220,
        ingredients: ["Potatoes", "Garlic", "Butter", "Cream"],
        tags: ["Creamy", "Comfort", "Classic"],
      },
      {
        name: "Steamed Vegetables",
        description: "Seasonal fresh vegetables",
        price: 5.99,
        category: "SIDE_DISH",
        preparationStation: "KITCHEN",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop",
        calories: 80,
        ingredients: ["Broccoli", "Carrots", "Zucchini", "Bell Peppers"],
        tags: ["Healthy", "Fresh", "Light"],
      },
      {
        name: "Caesar Salad",
        description: "Romaine lettuce with caesar dressing",
        price: 7.99,
        category: "SIDE_DISH",
        preparationStation: "KITCHEN",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 6,
        imageUrl:
          "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&auto=format&fit=crop",
        calories: 180,
        ingredients: ["Romaine", "Caesar Dressing", "Croutons", "Parmesan"],
        tags: ["Salad", "Classic", "Fresh"],
      },
      {
        name: "Mac and Cheese",
        description: "Creamy macaroni and cheese",
        price: 6.99,
        category: "SIDE_DISH",
        preparationStation: "KITCHEN",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 15,
        imageUrl:
          "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop",
        calories: 420,
        ingredients: ["Macaroni", "Cheddar", "Milk", "Butter"],
        tags: ["Cheesy", "Comfort", "Creamy"],
      },
      {
        name: "Coleslaw",
        description: "Creamy cabbage and carrot slaw",
        price: 3.99,
        category: "SIDE_DISH",
        preparationStation: "KITCHEN",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop",
        calories: 120,
        ingredients: ["Cabbage", "Carrots", "Mayonnaise", "Vinegar"],
        tags: ["Fresh", "Creamy", "Cold"],
      },
      {
        name: "Garlic Breadsticks",
        description: "Soft breadsticks with garlic butter",
        price: 4.99,
        category: "SIDE_DISH",
        preparationStation: "KITCHEN",
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w-800&auto=format&fit=crop",
        calories: 280,
        ingredients: ["Bread Dough", "Garlic", "Butter", "Herbs"],
        tags: ["Bread", "Garlic", "Warm"],
      },
    ],
  });
}
main()
  .then(async () => {
    await db.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await db.$disconnect();
    process.exit(1);
  });
