import db from "@/lib/db";

async function main() {
  await db.menuItem.createMany({
    data: [
      {
        name: "Bruschetta",
        description:
          "Toasted bread topped with fresh tomatoes, garlic, basil, and olive oil",
        price: 8.5,
        category: "APPETIZER",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1536739782508-c2388552aad3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxicnVzY2hldHRhJTIwYXBwZXRpemVyfGVufDF8fHx8MTc2NjMwNTI2OHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 180,
        ingredients: ["bread", "tomatoes", "garlic", "basil", "olive oil"],
        tags: ["vegetarian", "italian", "fresh"],
      },
      {
        name: "Spring Rolls",
        description:
          "Crispy vegetable spring rolls served with sweet chili sauce",
        price: 7.0,
        category: "APPETIZER",
        preparationStation: "FRY_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 15,
        imageUrl:
          "https://images.unsplash.com/photo-1695712641569-05eee7b37b6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcHJpbmclMjByb2xsc3xlbnwxfHx8fDE3NjYzMzA4Nzl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 220,
        ingredients: [
          "vegetables",
          "rice paper",
          "soy sauce",
          "sweet chili sauce",
        ],
        tags: ["vegetarian", "asian", "crispy"],
      },
      {
        name: "Buffalo Wings",
        description:
          "Spicy chicken wings tossed in buffalo sauce with blue cheese dip",
        price: 12.0,
        category: "APPETIZER",
        preparationStation: "FRY_STATION",
        isAvailable: false,
        isVegetarian: false,
        isSpicy: true,
        isAlcoholic: false,
        preparationTime: 20,
        imageUrl:
          "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwd2luZ3N8ZW58MXx8fHwxNzY2MzUzOTMyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 450,
        ingredients: [
          "chicken wings",
          "buffalo sauce",
          "blue cheese",
          "celery",
        ],
        tags: ["spicy", "chicken", "american"],
      },
      {
        name: "Caesar Salad",
        description:
          "Crisp romaine lettuce with parmesan, croutons and caesar dressing",
        price: 9.5,
        category: "APPETIZER",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYWVzYXIlMjBzYWxhZHxlbnwxfHx8fDE3NjYzNTAwMDd8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 280,
        ingredients: [
          "romaine lettuce",
          "parmesan",
          "croutons",
          "caesar dressing",
        ],
        tags: ["vegetarian", "salad", "classic"],
      },
      {
        name: "Garlic Bread",
        description: "Toasted bread with garlic butter and herbs",
        price: 6.0,
        category: "APPETIZER",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 12,
        imageUrl:
          "https://images.unsplash.com/photo-1573140401552-3fab0b24306f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYXJsaWMlMjBicmVhZHxlbnwxfHx8fDE3NjYzMzI4NzF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 320,
        ingredients: ["bread", "garlic", "butter", "parsley"],
        tags: ["vegetarian", "bread", "side"],
      },
      {
        name: "Fried Calamari",
        description: "Crispy squid rings served with marinara sauce and lemon",
        price: 13.0,
        category: "APPETIZER",
        preparationStation: "FRY_STATION",
        isAvailable: true,
        isVegetarian: false,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 18,
        imageUrl:
          "https://images.unsplash.com/photo-1734771219838-61863137b117?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYWxhbWFyaSUyMGZyaWVkfGVufDF8fHx8MTc2NjMzMDg3OXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 380,
        ingredients: ["squid", "flour", "marinara sauce", "lemon"],
        tags: ["seafood", "fried", "crispy"],
      },
      {
        name: "Caprese Salad",
        description: "Fresh mozzarella, tomatoes, basil with balsamic glaze",
        price: 10.0,
        category: "APPETIZER",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1595587870672-c79b47875c6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYXByZXNlJTIwc2FsYWR8ZW58MXx8fHwxNzY2Mzg0NjM3fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 240,
        ingredients: ["mozzarella", "tomatoes", "basil", "balsamic vinegar"],
        tags: ["vegetarian", "fresh", "italian"],
      },
      {
        name: "Soup of the Day",
        description:
          "Chef's special soup, ask your server for today's selection",
        price: 7.5,
        category: "APPETIZER",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1764015939059-2c5dee249315?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcmVhbXklMjBzb3VwJTIwYm93bHxlbnwxfHx8fDE3NjYxMzg5NjR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 180,
        ingredients: ["seasonal vegetables", "cream", "herbs", "spices"],
        tags: ["vegetarian", "soup", "comfort"],
      },
      {
        name: "Ribeye Steak",
        description:
          "12oz premium ribeye steak grilled to perfection with garlic butter",
        price: 32.0,
        category: "MAIN_COURSE",
        preparationStation: "GRILL_STATION",
        isAvailable: true,
        isVegetarian: false,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 25,
        imageUrl:
          "https://images.unsplash.com/photo-1728376336175-17dee7f07da2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGVhayUyMHBsYXRlfGVufDF8fHx8MTc2NjQwOTA3MXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 680,
        ingredients: ["ribeye steak", "garlic butter", "herbs", "sea salt"],
        tags: ["premium", "beef", "grilled"],
      },
      {
        name: "Sushi Platter",
        description:
          "Assorted nigiri and rolls with wasabi, ginger, and soy sauce",
        price: 28.0,
        category: "MAIN_COURSE",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: false,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 20,
        imageUrl:
          "https://images.unsplash.com/photo-1663334038419-71e6f82e333f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXNoaSUyMHBsYXR0ZXJ8ZW58MXx8fHwxNzY2NDA5MDcxfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 520,
        ingredients: ["sushi rice", "fresh fish", "nori", "avocado"],
        tags: ["seafood", "japanese", "fresh"],
      },
      {
        name: "Spicy Chicken Curry",
        description:
          "Tender chicken in a rich, aromatic curry sauce with jasmine rice",
        price: 18.0,
        category: "MAIN_COURSE",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: false,
        isSpicy: true,
        isAlcoholic: false,
        preparationTime: 30,
        imageUrl:
          "https://images.unsplash.com/photo-1631292784640-2b24be784d5d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwY3Vycnl8ZW58MXx8fHwxNzY2MzMyMzM5fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 580,
        ingredients: ["chicken", "curry spices", "coconut milk", "rice"],
        tags: ["spicy", "curry", "indian"],
      },
      {
        name: "Fish Tacos",
        description:
          "Three grilled fish tacos with cabbage slaw and chipotle mayo",
        price: 16.5,
        category: "MAIN_COURSE",
        preparationStation: "GRILL_STATION",
        isAvailable: false,
        isVegetarian: false,
        isSpicy: true,
        isAlcoholic: false,
        preparationTime: 18,
        imageUrl:
          "https://images.unsplash.com/photo-1604467715878-83e57e8bc129?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmaXNoJTIwdGFjb3N8ZW58MXx8fHwxNzY2MzI2NTU0fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 460,
        ingredients: ["white fish", "tortillas", "cabbage", "chipotle mayo"],
        tags: ["seafood", "mexican", "spicy"],
      },
      {
        name: "Margherita Pizza",
        description:
          "Classic pizza with fresh mozzarella, tomato sauce, and basil",
        price: 15.0,
        category: "MAIN_COURSE",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 15,
        imageUrl:
          "https://images.unsplash.com/photo-1617343251257-b5d709934ddd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2ZWdldGFyaWFuJTIwcGl6emF8ZW58MXx8fHwxNzY2MzY3MjU2fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 540,
        ingredients: ["pizza dough", "mozzarella", "tomato sauce", "basil"],
        tags: ["vegetarian", "italian", "classic"],
      },
      {
        name: "Lamb Chops",
        description: "Grilled lamb chops with rosemary and mint sauce",
        price: 34.0,
        category: "MAIN_COURSE",
        preparationStation: "GRILL_STATION",
        isAvailable: true,
        isVegetarian: false,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 28,
        imageUrl:
          "https://images.unsplash.com/photo-1692106914421-e04e1066bd62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYW1iJTIwY2hvcHN8ZW58MXx8fHwxNzY2MzM0NDcxfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 620,
        ingredients: ["lamb chops", "rosemary", "garlic", "mint sauce"],
        tags: ["premium", "lamb", "grilled"],
      },
      {
        name: "Seafood Paella",
        description:
          "Traditional Spanish rice dish with shrimp, mussels, and calamari",
        price: 26.0,
        category: "MAIN_COURSE",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: false,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 35,
        imageUrl:
          "https://images.unsplash.com/photo-1623961990059-28356e226a77?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzZWFmb29kJTIwcGFlbGxhfGVufDF8fHx8MTc2NjQwOTA3Mnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 640,
        ingredients: ["rice", "shrimp", "mussels", "saffron", "calamari"],
        tags: ["seafood", "spanish", "rice"],
      },
      {
        name: "Gourmet Burger",
        description:
          "Wagyu beef burger with aged cheddar, caramelized onions, and truffle aioli",
        price: 19.0,
        category: "MAIN_COURSE",
        preparationStation: "GRILL_STATION",
        isAvailable: true,
        isVegetarian: false,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 20,
        imageUrl:
          "https://images.unsplash.com/photo-1550547660-d9450f859349?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnb3VybWV0JTIwYnVyZ2VyfGVufDF8fHx8MTc2NjEwMTkxMHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 780,
        ingredients: [
          "wagyu beef",
          "cheddar",
          "onions",
          "truffle aioli",
          "brioche bun",
        ],
        tags: ["premium", "burger", "beef"],
      },
      {
        name: "Molten Chocolate Lava Cake",
        description:
          "Warm chocolate cake with a gooey center, served with vanilla ice cream",
        price: 9.0,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 12,
        imageUrl:
          "https://images.unsplash.com/photo-1673551490812-eaee2e9bf0ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaG9jb2xhdGUlMjBsYXZhJTIwY2FrZXxlbnwxfHx8fDE3NjYzMzA0MjV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 520,
        ingredients: [
          "dark chocolate",
          "butter",
          "eggs",
          "sugar",
          "vanilla ice cream",
        ],
        tags: ["chocolate", "warm", "indulgent"],
      },
      {
        name: "Crème Brûlée",
        description: "Classic French custard with caramelized sugar crust",
        price: 8.5,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1676300184943-09b2a08319a3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcmVtZSUyMGJydWxlZXxlbnwxfHx8fDE3NjYzODQ2NDB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 380,
        ingredients: ["cream", "egg yolks", "vanilla", "sugar"],
        tags: ["french", "classic", "creamy"],
      },
      {
        name: "Apple Pie",
        description: "Homemade apple pie with cinnamon and a flaky crust",
        price: 7.5,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isAvailable: false,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1621743478914-cc8a86d7e7b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcHBsZSUyMHBpZXxlbnwxfHx8fDE3NjYzNDY4ODh8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 420,
        ingredients: ["apples", "cinnamon", "sugar", "pie crust"],
        tags: ["american", "fruit", "warm"],
      },
      {
        name: "Ice Cream Sundae",
        description:
          "Three scoops of ice cream with chocolate sauce, whipped cream, and cherry",
        price: 8.0,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1657225953401-5f95007fc8e0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpY2UlMjBjcmVhbSUyMHN1bmRhZXxlbnwxfHx8fDE3NjYzODA5Njh8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 480,
        ingredients: [
          "ice cream",
          "chocolate sauce",
          "whipped cream",
          "cherry",
        ],
        tags: ["cold", "sweet", "classic"],
      },
      {
        name: "Panna Cotta",
        description: "Italian cream dessert with berry compote",
        price: 9.5,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1488477181946-6428a0291777?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYW5uYSUyMGNvdHRhfGVufDF8fHx8MTc2NjQwOTA3NHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 320,
        ingredients: ["cream", "sugar", "vanilla", "berries", "gelatin"],
        tags: ["italian", "creamy", "elegant"],
      },
      {
        name: "Fresh Fruit Tart",
        description:
          "Buttery tart shell filled with custard and topped with seasonal fruits",
        price: 10.0,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1620980776848-84ac10194945?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcnVpdCUyMHRhcnR8ZW58MXx8fHwxNzY2MzczMjY5fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 380,
        ingredients: [
          "pastry cream",
          "tart shell",
          "strawberries",
          "kiwi",
          "blueberries",
        ],
        tags: ["fresh", "fruit", "elegant"],
      },
      {
        name: "Macarons Box",
        description: "Assorted French macarons in various flavors (6 pieces)",
        price: 12.0,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 3,
        imageUrl:
          "https://images.unsplash.com/photo-1679942262057-d5732f732841?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWNhcm9ucyUyMGRlc3NlcnR8ZW58MXx8fHwxNzY2NDA5MDc0fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 420,
        ingredients: [
          "almond flour",
          "sugar",
          "egg whites",
          "various fillings",
        ],
        tags: ["french", "colorful", "delicate"],
      },
      {
        name: "Tiramisu",
        description:
          "Classic Italian dessert with coffee-soaked ladyfingers and mascarpone",
        price: 9.5,
        category: "DESSERT",
        preparationStation: "DESSERT_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1714385905983-6f8e06fffae1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aXJhbWlzdSUyMGRlc3NlcnR8ZW58MXx8fHwxNzY2MDQxMDY0fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 450,
        ingredients: [
          "mascarpone",
          "ladyfingers",
          "espresso",
          "marsala wine",
          "cocoa",
        ],
        tags: ["italian", "coffee", "classic"],
      },
      {
        name: "Espresso",
        description: "Rich and bold Italian espresso shot",
        price: 3.5,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 2,
        imageUrl:
          "https://images.unsplash.com/photo-1485808191679-5f86510681a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlc3ByZXNzbyUyMGNvZmZlZXxlbnwxfHx8fDE3NjYzMDk0MTR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 5,
        ingredients: ["espresso beans", "water"],
        tags: ["coffee", "hot", "strong"],
      },
      {
        name: "Green Tea",
        description: "Premium Japanese green tea",
        price: 4.0,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1606377695906-236fdfcef767?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxncmVlbiUyMHRlYXxlbnwxfHx8fDE3NjYzODA5Njl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 0,
        ingredients: ["green tea leaves", "water"],
        tags: ["tea", "healthy", "hot"],
      },
      {
        name: "Acai Smoothie Bowl",
        description: "Acai berry smoothie topped with granola and fresh fruits",
        price: 9.0,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1590301157284-ab2f8707bdc1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbW9vdGhpZSUyMGJvd2x8ZW58MXx8fHwxNzY2Mzc3ODMzfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 320,
        ingredients: ["acai berries", "banana", "granola", "honey", "berries"],
        tags: ["healthy", "fresh", "vegan"],
      },
      {
        name: "Fresh Lemonade",
        description: "Freshly squeezed lemonade with mint",
        price: 5.0,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isAvailable: false,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1616434963473-030c8f1ce663?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpY2VkJTIwbGVtb25hZGV8ZW58MXx8fHwxNzY2NDA5MDc1fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 120,
        ingredients: ["lemons", "sugar", "water", "mint", "ice"],
        tags: ["refreshing", "cold", "citrus"],
      },
      {
        name: "Hot Chocolate",
        description: "Rich hot chocolate with whipped cream and marshmallows",
        price: 5.5,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob3QlMjBjaG9jb2xhdGV8ZW58MXx8fHwxNzY2MzIyOTgyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 280,
        ingredients: ["chocolate", "milk", "whipped cream", "marshmallows"],
        tags: ["chocolate", "hot", "sweet"],
      },
      {
        name: "Strawberry Milkshake",
        description: "Creamy milkshake made with fresh strawberries",
        price: 7.0,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1648178628415-b410fc1d58bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaWxrc2hha2UlMjBnbGFzc3xlbnwxfHx8fDE3NjY0MDkwNzZ8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 380,
        ingredients: ["strawberries", "ice cream", "milk", "sugar"],
        tags: ["sweet", "cold", "fruity"],
      },
      {
        name: "Iced Tea",
        description: "Refreshing iced tea with lemon",
        price: 4.5,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 3,
        imageUrl:
          "https://images.unsplash.com/photo-1499638673689-79a0b5115d87?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpY2VkJTIwdGVhfGVufDF8fHx8MTc2NjM5OTYxNXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 80,
        ingredients: ["black tea", "lemon", "sugar", "ice"],
        tags: ["refreshing", "cold", "tea"],
      },
      {
        name: "Cappuccino",
        description: "Classic Italian coffee with steamed milk and foam",
        price: 4.5,
        category: "BEVERAGE",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 4,
        imageUrl:
          "https://images.unsplash.com/photo-1611564494260-6f21b80af7ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2ZmZWUlMjBsYXR0ZXxlbnwxfHx8fDE3NjYwNDc2Nzh8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 120,
        ingredients: ["espresso", "steamed milk", "milk foam"],
        tags: ["coffee", "hot", "classic"],
      },
      {
        name: "Margarita",
        description: "Classic tequila cocktail with lime and salt rim",
        price: 12.0,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1655546837806-76a6dd54ee2b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYXJnYXJpdGElMjBjb2NrdGFpbHxlbnwxfHx8fDE3NjYzMjY5MzN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 220,
        ingredients: ["tequila", "triple sec", "lime juice", "salt"],
        tags: ["cocktail", "tequila", "classic"],
      },
      {
        name: "Whiskey Old Fashioned",
        description: "Premium bourbon with bitters, sugar, and orange peel",
        price: 14.0,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1667928916119-2c2c5fe67b90?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aGlza2V5JTIwZ2xhc3N8ZW58MXx8fHwxNjYzMzU1MzJ8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 180,
        ingredients: ["bourbon", "bitters", "sugar", "orange peel"],
        tags: ["whiskey", "classic", "strong"],
      },
      {
        name: "Draft Beer",
        description: "Selection of local and imported beers on tap",
        price: 7.0,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 2,
        imageUrl:
          "https://images.unsplash.com/photo-1615332579037-3c44b3660b53?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWVyJTIwcGludHxlbnwxfHx8fDE3NjY0MDkwNzd8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 150,
        ingredients: ["beer"],
        tags: ["beer", "cold", "refreshing"],
      },
      {
        name: "Cosmopolitan",
        description: "Vodka cocktail with cranberry, lime, and triple sec",
        price: 13.0,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isAvailable: false,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1556855810-ac404aa91e85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3Ntb3BvbGl0YW4lMjBjb2NrdGFpbHxlbnwxfHx8fDE3NjYzMjY5MzV8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 200,
        ingredients: ["vodka", "cranberry juice", "triple sec", "lime juice"],
        tags: ["cocktail", "vodka", "fruity"],
      },
      {
        name: "Sangria Pitcher",
        description: "Red wine sangria with fresh fruits (serves 4)",
        price: 28.0,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1712219003003-23f067d78e55?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYW5ncmlhJTIwcGl0Y2hlcnxlbnwxfHx8fDE3NjY0MDkwNzh8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 180,
        ingredients: ["red wine", "brandy", "orange juice", "fresh fruits"],
        tags: ["wine", "fruity", "sharing"],
      },
      {
        name: "Champagne",
        description: "Premium French champagne",
        price: 18.0,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 2,
        imageUrl:
          "https://images.unsplash.com/photo-1546567379-1af2e0d527e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGFtcGFnbmUlMjBnbGFzc2VzfGVufDF8fHx8MTc2NjQwOTA3OHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 90,
        ingredients: ["champagne"],
        tags: ["champagne", "sparkling", "celebration"],
      },
      {
        name: "Dirty Martini",
        description: "Classic vodka or gin martini with olive brine",
        price: 13.5,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 4,
        imageUrl:
          "https://images.unsplash.com/photo-1638884896143-f1b2501e9a61?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYXJ0aW5pJTIwZ2xhc3N8ZW58MXx8fHwxNzY2NDA5MDc4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 160,
        ingredients: ["vodka", "dry vermouth", "olive brine", "olives"],
        tags: ["cocktail", "classic", "strong"],
      },
      {
        name: "Mojito",
        description: "Refreshing rum cocktail with mint, lime, and soda",
        price: 12.0,
        category: "ALCOHOLIC",
        preparationStation: "BAR",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: true,
        preparationTime: 6,
        imageUrl:
          "https://images.unsplash.com/photo-1556855810-ac404aa91e85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2NrdGFpbCUyMGdsYXNzfGVufDF8fHx8MTc2NjEzODk2N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 210,
        ingredients: ["white rum", "mint", "lime juice", "sugar", "soda water"],
        tags: ["cocktail", "rum", "refreshing"],
      },
      {
        name: "Loaded Nachos",
        description:
          "Crispy tortilla chips with cheese, jalapeños, sour cream, and guacamole",
        price: 10.0,
        category: "SNACK",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: true,
        isAlcoholic: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1669624272709-c5b91f66b1b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYWNob3MlMjBjaGVlc2V8ZW58MXx8fHwxNzY2MzgwOTY2fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 520,
        ingredients: [
          "tortilla chips",
          "cheese",
          "jalapeños",
          "sour cream",
          "guacamole",
        ],
        tags: ["spicy", "mexican", "sharing"],
      },
      {
        name: "Truffle Popcorn",
        description: "Gourmet popcorn with truffle oil and parmesan",
        price: 6.0,
        category: "SNACK",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1695866648701-444366d3abe3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3Bjb3JuJTIwYm93bHxlbnwxfHx8fDE3NjY0MDkwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 180,
        ingredients: ["popcorn", "truffle oil", "parmesan", "salt"],
        tags: ["vegetarian", "gourmet", "light"],
      },
      {
        name: "Soft Pretzel",
        description: "Warm Bavarian-style pretzel with beer cheese dip",
        price: 7.5,
        category: "SNACK",
        preparationStation: "KITCHEN",
        isAvailable: false,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1607103058027-4c5b42b86a60?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcmV0emVsJTIwc29mdHxlbnwxfHx8fDE3NjY0MDkwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 340,
        ingredients: ["pretzel dough", "salt", "beer cheese"],
        tags: ["vegetarian", "warm", "bavarian"],
      },
      {
        name: "Chips & Salsa",
        description: "Crispy tortilla chips with fresh house-made salsa",
        price: 5.5,
        category: "SNACK",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: true,
        isAlcoholic: false,
        preparationTime: 3,
        imageUrl:
          "https://images.unsplash.com/photo-1734027899096-291063588ab3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGlwcyUyMHNhbHNhfGVufDF8fHx8MTc2NjQwOTA3OXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 220,
        ingredients: [
          "tortilla chips",
          "tomatoes",
          "onions",
          "cilantro",
          "lime",
        ],
        tags: ["vegan", "spicy", "mexican"],
      },
      {
        name: "Crispy Onion Rings",
        description: "Beer-battered onion rings with ranch dipping sauce",
        price: 8.0,
        category: "SNACK",
        preparationStation: "FRY_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 12,
        imageUrl:
          "https://images.unsplash.com/photo-1639024471283-03518883512d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvbmlvbiUyMHJpbmdzfGVufDF8fHx8MTc2NjM5OTY5N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 380,
        ingredients: ["onions", "beer batter", "ranch dressing"],
        tags: ["vegetarian", "fried", "crispy"],
      },
      {
        name: "Mozzarella Sticks",
        description: "Breaded mozzarella cheese sticks with marinara sauce",
        price: 9.0,
        category: "SNACK",
        preparationStation: "FRY_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1734774924912-dcbb467f8599?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb3p6YXJlbGxhJTIwc3RpY2tzfGVufDF8fHx8MTc2NjQwOTA4MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 420,
        ingredients: ["mozzarella", "breadcrumbs", "marinara sauce"],
        tags: ["vegetarian", "cheese", "fried"],
      },
      {
        name: "Edamame",
        description: "Steamed soybeans with sea salt",
        price: 5.0,
        category: "SNACK",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1575262599410-837a72005862?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlZGFtYW1lJTIwYm93bHxlbnwxfHx8fDE3NjY0MDkwODB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 120,
        ingredients: ["edamame", "sea salt"],
        tags: ["vegan", "healthy", "japanese"],
      },
      {
        name: "French Fries",
        description: "Crispy golden fries with sea salt",
        price: 4.0,
        category: "SNACK",
        preparationStation: "FRY_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmVuY2glMjBmcmllc3xlbnwxfHx8fDE3NjYwNjMzNTJ8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 320,
        ingredients: ["potatoes", "oil", "salt"],
        tags: ["vegan", "classic", "crispy"],
      },
      {
        name: "Garlic Mashed Potatoes",
        description: "Creamy mashed potatoes with roasted garlic and butter",
        price: 6.5,
        category: "SIDE_DISH",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1707616954324-99c89a78a20d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYXNoZWQlMjBwb3RhdG9lc3xlbnwxfHx8fDE3NjY0MDkwODB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 240,
        ingredients: ["potatoes", "butter", "cream", "garlic", "herbs"],
        tags: ["vegetarian", "comfort", "creamy"],
      },
      {
        name: "Coleslaw",
        description: "Fresh cabbage slaw with tangy dressing",
        price: 5.0,
        category: "SIDE_DISH",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 5,
        imageUrl:
          "https://images.unsplash.com/photo-1708388064941-de7a9f879bf9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2xlc2xhdyUyMGJvd2x8ZW58MXx8fHwxNzY2NDA5MDgxfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 150,
        ingredients: ["cabbage", "carrots", "mayonnaise", "vinegar", "sugar"],
        tags: ["vegetarian", "fresh", "tangy"],
      },
      {
        name: "Steamed Broccoli",
        description: "Fresh broccoli florets steamed and seasoned",
        price: 5.5,
        category: "SIDE_DISH",
        preparationStation: "KITCHEN",
        isAvailable: false,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 8,
        imageUrl:
          "https://images.unsplash.com/photo-1609190756694-1580c87618eb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGVhbWVkJTIwYnJvY2NvbGl8ZW58MXx8fHwxNzY2NDA5MDgxfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 55,
        ingredients: ["broccoli", "butter", "salt", "pepper"],
        tags: ["vegan", "healthy", "green"],
      },
      {
        name: "Herb Rice Pilaf",
        description: "Aromatic rice cooked with herbs and vegetables",
        price: 6.0,
        category: "SIDE_DISH",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 15,
        imageUrl:
          "https://images.unsplash.com/photo-1634324092536-74480096b939?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyaWNlJTIwcGlsYWZ8ZW58MXx8fHwxNzY2MzM5OTUyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 220,
        ingredients: ["rice", "onions", "herbs", "butter", "vegetables"],
        tags: ["vegetarian", "aromatic", "rice"],
      },
      {
        name: "Grilled Corn on the Cob",
        description: "Sweet corn grilled with herb butter",
        price: 5.5,
        category: "SIDE_DISH",
        preparationStation: "GRILL_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 12,
        imageUrl:
          "https://images.unsplash.com/photo-1708077810069-0e082d9558dd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3JuJTIwY29iJTIwZ3JpbGxlZHxlbnwxfHx8fDE3NjY0MDkwODF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 180,
        ingredients: ["corn", "butter", "herbs", "salt"],
        tags: ["vegetarian", "sweet", "grilled"],
      },
      {
        name: "Sweet Potato Fries",
        description: "Crispy sweet potato fries with honey dipping sauce",
        price: 7.0,
        category: "SIDE_DISH",
        preparationStation: "FRY_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 15,
        imageUrl:
          "https://images.unsplash.com/photo-1598679253544-2c97992403ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzd2VldCUyMHBvdGF0byUyMGZyaWVzfGVufDF8fHx8MTc2NjQwOTA4Mnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 280,
        ingredients: ["sweet potatoes", "oil", "honey", "spices"],
        tags: ["vegetarian", "sweet", "crispy"],
      },
      {
        name: "Sautéed Mushrooms",
        description: "Mixed mushrooms sautéed in garlic butter",
        price: 8.0,
        category: "SIDE_DISH",
        preparationStation: "KITCHEN",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 10,
        imageUrl:
          "https://images.unsplash.com/photo-1607835498598-29e40be5eed0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYXV0ZWVkJTIwbXVzaHJvb21zfGVufDF8fHx8MTc2NjQwOTA4Mnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 120,
        ingredients: ["mushrooms", "garlic", "butter", "thyme", "parsley"],
        tags: ["vegetarian", "savory", "gourmet"],
      },
      {
        name: "Grilled Vegetables",
        description:
          "Seasonal vegetables grilled to perfection with balsamic glaze",
        price: 6.5,
        category: "SIDE_DISH",
        preparationStation: "GRILL_STATION",
        isAvailable: true,
        isVegetarian: true,
        isSpicy: false,
        isAlcoholic: false,
        preparationTime: 12,
        imageUrl:
          "https://images.unsplash.com/photo-1633862033803-7abafaf9bcb9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzaWRlJTIwZGlzaCUyMHZlZ2V0YWJsZXN8ZW58MXx8fHwxNzY2MTMwMTIxfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
        calories: 140,
        ingredients: [
          "zucchini",
          "bell peppers",
          "eggplant",
          "balsamic",
          "olive oil",
        ],
        tags: ["vegan", "healthy", "grilled"],
      },
    ],
  });
}
main()
  .then(async () => {
    await db.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await db.$disconnect();
    process.exit(1);
  });
